src/Fusion.WebApp/Models/Developer/LogViewModel.cs
namespace Fusion.WebApp.Models
{
    using FlightDeck.DomainShared;
    using System;
    using System.Collections.Generic;
    
    public class LogViewModel
    {
        public DateTime Date { get; set; }
        public string Level { get; set; }
        public IEnumerable<Log> Entries { get; set; }
    }
}

src/Fusion.WebApp/Controllers/DeveloperController.cs
using FlightDeck.DomainShared;
using FlightDeck.ServiceInterfaces;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Fusion.WebApp.Controllers
{
    [Authorize(Users="logviewer")]
    public class DeveloperController : FusionBaseController
    {
        private ILogReader _logReader;

        public ILogReader LogReader
        {
            private get
            {
                if (_logReader == null)
                    _logReader = ServiceFactory.GetService<ILogReader>(this);
                return _logReader;
            }
            set //TODO internal? 
            {
                _logReader = value;
            }
        }

        public ActionResult Index()
        {
            return View();
        }

        public ActionResult Log(string date, string level)
        {
            DateTime d;
            if (!DateTime.TryParse(date, out d))
            {
                d = DateTime.Now;
            }

            var entries = LogReader.GetAll(d, level) ?? new List<Log>();

            var model = new Fusion.WebApp.Models.LogViewModel
                {
                    Date = d,
                    Level = level,
                    Entries = entries.OrderBy(x => x.Date)
                };

            return View(model);
        }
    }
}

src/Fusion.WebApp/Views/Developer/Index.cshtml
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
}

<h2>Developer resources</h2>

<h4>v @Fusion.WebApp.AppSettings.Version.ToString() - @Fusion.WebApp.AppInfo.DeploymentDate.ToString("dd MMM yyyy")</h4>

<ul>
    <li>@Html.ActionLink("view log", "Log")</li>
</ul>

src/Fusion.WebApp/Views/Developer/Log.cshtml
@model Fusion.WebApp.Models.LogViewModel
@{
    ViewBag.Title = "Log";
    Layout = "~/Views/Shared/_LayoutEmpty.cshtml";
}

<h2>Log</h2>

<h3>Showing for date: @Model.Date.ToString("dd MMM yy") @Html.WriteIfValueExists(Model.Level, ", and level: " + Model.Level)</h3>

@using (Html.BeginForm("Log", "Developer", FormMethod.Get))
{
    <p>
        <label for="date">Date (dd/mm/yyyy): </label>
        <input type="text" name="date" />
        <label for="level"></label>
        <select name="level">
            <option value="">ALL</option>
            <option value="ERROR">ERROR</option>
        </select>
        <input type="submit" value="Get" />
    </p>
}

@if (Model.Entries.Any())
{
    <table border="1">
        <tr>
            <th>Date</th><th>Thread</th><th>Level</th><th>Logger</th><th>Message</th><th>Exception</th>
        </tr>
        @foreach (var log in Model.Entries)
        {
            <tr>
                <td nowrap>@log.Date.ToString("yyyy-MM-dd HH:mm:ss.ff")</td>
                <td>@log.Thread</td>
                <td>@log.Level</td>
                <td>@log.Logger</td>
                <td>@log.Message</td>
                <td>@log.Exception</td>
            </tr>
        }
    </table>
}
else
{
    <p>No entries.</p>
}