src/Fusion.WebApp/Models/Scheme/AdditSchemeModel.cs
using FlightDeck.DomainShared;
using FlightDeck.ServiceInterfaces;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.Web;

namespace Fusion.WebApp.Models
{
    public class AdditSchemeViewModel
    {
        public AdditSchemeViewModel()
        {
            this.Documents = new List<HttpPostedFileBase>();
            this.DocumentIds = new List<int>();
            this.DocumentNames = new List<string>();
            this.DocumentFileNames = new List<string>();
            this.DeleteDocuments = new List<int>();
        }

        public AdditSchemeResult Result { get; set; }
        public int Id { get; set; }

        [DataType(DataType.Text)]
        public string CurrentSchemeName { get; set; }

        public bool IsEditScheme { get; set; }

        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Text)]
        [Display(Name = "Scheme name")]
        public string NewSchemeName { get; set; }

        public bool HasLogo { get; set; }

        [Display(Name = "Company logo")]
        public HttpPostedFileBase Logo { get; set; }

        [Display(Name = "Restricted")]
        public bool IsRestricted { get; set; }

        [Display(Name = "Scheme import file")]
        public HttpPostedFileBase SchemeData { get; set; }

        [Display(Name = "Accounting downloads password")]
        [DataType(DataType.Password)]
        public string AccountingDownloadsPassword { get; set; }

        [Display(Name = "Source")]
        public string ExportFile { get; set; }

        public string ImportFileSpreadsheetName { get; set; }

        [Display(Name = "Documents")]
        public IList<HttpPostedFileBase> Documents { get; set; }

        public IList<String> DocumentNames { get; set; }
        public IList<String> DocumentFileNames { get; set; }
        public IList<int> DocumentIds { get; set; }
        public IList<int> DeleteDocuments { get; set; }
        public string ImportErrorAt { get; set; }
        public string ImportErrorDetails { get; set; }
        public bool SourceXmlExists { get; set; }
    }
}

src/Fusion.WebApp/Models/Scheme/FindSchemeViewModel.cs
namespace Fusion.WebApp.Models
{
    using FlightDeck.ServiceInterfaces;
    using System.ComponentModel.DataAnnotations;
    
    public class FindSchemeViewModel
    {
        public ResultEnum Result { get; set; }

        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Text)]
        [Display(Name = "Search scheme details")]
        public string FindSchemeName { get; set; }

        public SchemeRestrictionStatus RestrictionStatus { get; set; }
        public string SubmitLabel { get; set; }
        public bool ShowListAll { get; set; }

        public FindSchemeViewModel()
        {
            RestrictionStatus = SchemeRestrictionStatus.All;
        }
    }
}

src/Fusion.WebApp/Models/Scheme/ListSchemeViewModel.cs
using FlightDeck.DomainShared;
using FlightDeck.ServiceInterfaces;
using System.Collections.Generic;

namespace Fusion.WebApp.Models
{
    public class ListSchemeViewModel
    {
        public List<IScheme> Schemes { get; set; }
    }
}

src/Fusion.WebApp/Models/Scheme/ManageSchemeViewModel.cs
using FlightDeck.DomainShared;
using FlightDeck.ServiceInterfaces;
using System.Collections.Generic;

namespace Fusion.WebApp.Models
{
    public class ManageSchemeViewModel
    {
        public FindSchemeViewModel FindSchemeViewModel = new FindSchemeViewModel();
        public AdditSchemeViewModel AdditSchemeViewModel = new AdditSchemeViewModel();
        public ListSchemeViewModel ListSchemeViewModel = new ListSchemeViewModel();
        public IEnumerable<IScheme> SchemeImportHistory = new List<IScheme>();
    }
}

src/Fusion.WebApp/Models/Scheme/SchemeNameUpdateModel.cs
using System.ComponentModel.DataAnnotations;

namespace Fusion.WebApp.Models
{
    public class SchemeNameUpdateModel : UpdateModel<ResultEnum>
    {
        [DataType(DataType.Text)]
        [Display(Name = "Scheme name")]
        public string SchemeName { get; set; }
        public int SchemeDetailId { get; set; }
        public bool IsFavourite { get; set; }
    }
}

src/Fusion.WebApp/Models/Shared/SchemeViewModel.cs
namespace Fusion.WebApp.Models
{
    using FlightDeck.DomainShared;
    using FlightDeck.ServiceInterfaces;
    using System;
    using System.Collections.Generic;

    public class SchemeViewModel
    {
        private readonly IScheme _scheme;

        public SchemeViewModel(IScheme scheme)
        {
            _scheme = scheme;
        }

        public IScheme SchemeSummary { get { return _scheme; } }
        public IPensionScheme SchemeData { get { return _scheme.PensionScheme; } }

        // shorts cuts to help the views stay as dumb as possible
        public string SchemeName { get { return _scheme.SchemeName; } }
        public DateTime RefreshDate { get { return _scheme.PensionScheme.RefreshDate; } }
        public IBasis CurrentBasis { get { return _scheme.PensionScheme.CurrentBasis; } }
        public string CurrentBasisName { get { return _scheme.PensionScheme.CurrentBasis.Name; } }
        public BasisType CurrentBasisType { get { return _scheme.PensionScheme.CurrentBasis.BasisType; } }
        public IEnumerable<BasisType> BasisTypes { get { return _scheme.PensionScheme.GetBasisTypes(); } }
        public IList<SchemeDocument> Documents { get { return _scheme.Documents; } }
        public string CurrencySymbol { get { return _scheme.CurrencySymbol; } }
        public AccountingSettings AccountingSettings { get { return _scheme.PensionScheme.AccountingSettings; } }
    }
}

src/Fusion.WebApp/Models/Users/FindUserViewModel.cs
using System.ComponentModel.DataAnnotations;

namespace Fusion.WebApp.Models
{
    public class FindUserViewModel
    {
        public ResultEnum Result { get; set; }

        [Required(ErrorMessage = "Required")]
        [DataType(DataType.Text)]
        [Display(Name = "Search user details")]
        public string FindUserName { get; set; }
    }
}

src/Fusion.WebApp/Models/Users/ListUserViewModel.cs
using System.Collections.Generic;

namespace Fusion.WebApp.Models
{
    public class ListUserViewModel
    {
        public List<UserListItem> Users { get; set; }
        public UserListParams Params { get; set; }
    }
}

src/Fusion.WebApp/Models/Users/ManageUserViewModel.cs
namespace Fusion.WebApp.Models
{
    public class ManageUserViewModel
    {
        public bool IsEditing { get; set; }
        public string UsernameSaved { get; set; }
        public FindUserViewModel FindUserViewModel = new FindUserViewModel();
        public AdditUserViewModel AdditUserViewModel = new AdditUserViewModel();
        public ListUserViewModel ListUserViewModel = new ListUserViewModel();
    }
}

src/Fusion.WebApp/Models/Users/UserListItem.cs
namespace Fusion.WebApp.Models
{
    using FlightDeck.DomainShared;
    using System.Collections.Generic;
    
    public class UserListItem
    {
        public UserListItem()
        {
            Schemes = new List<SchemeDetail>();
        }

        public int Id { get; set; }
        public string UserName { get; set; }
        public string Forename { get; set; }
        public string Surname { get; set; }
        public string Email { get; set; }
        public RoleType Role { get; set; }
        public IEnumerable<SchemeDetail> Schemes { get; set; }
        public bool IsLocked { get; set; }
    }
}

src/Fusion.WebApp/Models/Users/UserListParams.cs
using FlightDeck.DomainShared;
namespace Fusion.WebApp.Models
{
    public class UserListParams
    {
        public int TotalMatches { get; set; }
        public int PageNumber { get; set; }
        public bool NameDescending { get; set; }
        public RoleType? RoleFilter { get; set; }
        public string SchemeName { get; set; }
    }
}

src/Fusion.WebApp/Controllers/SchemeController.cs
using FlightDeck.DomainShared;
using FlightDeck.ServiceInterfaces;
using FlightDeck.Services;
using Fusion.WebApp.Models;
using Fusion.WebApp.Filters;
using Fusion.WebApp.Models.Attributes;
using Fusion.WebApp.Services;
using System;
using System.Collections.Generic;
using System.Drawing;
using System.IO;
using System.Linq;
using System.Web.Mvc;
using System.Web.Security;
using System.Xml.Linq;
using WebMatrix.WebData;
using log4net;

namespace Fusion.WebApp.Controllers
{
    [Authorize]
    [OutputCache(Duration=0, NoStore=true, Location = System.Web.UI.OutputCacheLocation.None)]
    public class SchemeController : FusionBaseController
    {
        IPensionSchemeService _pensionSchemeService;
        public IPensionSchemeService PensionSchemeService
        {
            get
            {
                if (_pensionSchemeService == null) 
                    _pensionSchemeService = ServiceFactory.GetService<IPensionSchemeService>(this); 
                return _pensionSchemeService;
            }
            set
            {
                _pensionSchemeService = value;
            }
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [UserAdmit]
        public ActionResult Manage(int? id)
        {
            var model = new ManageSchemeViewModel();
            if (id.HasValue)
            {
                var scheme = PensionSchemeService.GetSummary(id.Value);
                if (scheme != null)
                {
                    model.AdditSchemeViewModel = mapSchemeDetailToAddit(scheme);
                    model.SchemeImportHistory = new List<IScheme> { scheme };
                }
            }
            else if (TempData.ContainsKey("ManageSchemeViewModel"))
            {
                model = (ManageSchemeViewModel)TempData["ManageSchemeViewModel"];
            }
            if (TempData.ContainsKey("AdditSchemeViewModel")) model.AdditSchemeViewModel = (AdditSchemeViewModel)TempData["AdditSchemeViewModel"];

            ViewBag.ReturnUrl = Url.Action("Manage");
            return View("Manage", model);
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        public ActionResult ListAll()
        {
            IEnumerable<IScheme> schemes = null;

            try
            {
                schemes = PensionSchemeService.GetAllSummaries().OrderBy(s => s.SchemeName);

                var model = new ManageSchemeViewModel
                {
                    ListSchemeViewModel = new ListSchemeViewModel
                    {
                        Schemes = schemes.ToList()
                    }
                };

                return View("List", model);
            }
            catch (Exception ex) 
            {
                LogManager.GetLogger(this.GetType()).ErrorFormat("User: {0}. {1}", User.Identity.Name, ex);
            }

            return View("List"); //no model and error message rendered for user.
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        public ActionResult Download(int id)
        {
            var source = PensionSchemeService.GetSchemeSource(id);

            if (source == null)
                return new EmptyResult();

            var schemeName = PensionSchemeService.GetSummary(id).SchemeName;

            var ms = new MemoryStream();
            source.Save(ms);
            ms.Position = 0;

            // force a 'save as...' prompt rather than linking directly to the xml output
            var cd = new System.Net.Mime.ContentDisposition
            {
                FileName = schemeName + ".xml",
                Inline = false,
            };
            ControllerContext.HttpContext.Response.AppendHeader("Content-Disposition", cd.ToString());

            return File(ms, "text/xml");
        }

        [HttpGet]
        public ActionResult List(SchemeRestrictionStatus state = SchemeRestrictionStatus.All)
        {
            return Json(GetSchemes(state), JsonRequestBehavior.AllowGet);
        }

        [HttpGet]
        public ActionResult Logo(String id = null)
        {
            byte[] logo = null;
            if (id == null)
            {
                logo = Scheme.Logo;
            }
            else
            {
                logo = PensionSchemeService.GetSummaryByName(id).Logo;
            }
            return new FileContentResult(logo, "image/png");
        }
        
        [HttpGet]
        public ActionResult Document(int id)
        {
            var doc = Scheme.Documents.SingleOrDefault(d => d.SchemeDocumentId == id);
            return new FileContentResult(doc.Content, doc.ContentType);
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [UserAdmit]
        public ActionResult Add()
        {
            ViewBag.ReturnUrl = Url.Action("Manage");
            return View("Manage", new ManageSchemeViewModel());
        }

        [HttpPost]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [ValidateAntiForgeryToken]
        public ActionResult Add(AdditSchemeViewModel model)
        {
            return addit(model);
        }

        [HttpGet]
        public ActionResult Edit()
        {
            return RedirectToAction("Manage");
        }

        [HttpPost]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [ValidateAntiForgeryToken]
        public ActionResult Edit(AdditSchemeViewModel model)
        {
            if (ControllerContext.HttpContext.Request["update"] != null)
            {
                var refresh = string.Equals(model.CurrentSchemeName, Scheme != null ? Scheme.SchemeName : string.Empty);

                var result = addit(model);

                if (refresh) SessionManager.RefreshScheme();

                return result;
            }
            else
            {
                return delete(model);
            }
        }

        [HttpGet]
        public ActionResult Find()
        {
            return RedirectToAction("Manage");
        }

        [HttpPost]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        public ActionResult Find(FindSchemeViewModel model)
        {
            ViewBag.ReturnUrl = Url.Action("Manage");

            IScheme scheme = null;

            if (model.FindSchemeName != null)
            {
                try
                {
                    scheme = PensionSchemeService.GetSummaryByName(model.FindSchemeName);
                }
                catch { }
            }

            if (scheme != null)
            {
                var editModel = new ManageSchemeViewModel();
                editModel.AdditSchemeViewModel = mapSchemeDetailToAddit(scheme);
                editModel.AdditSchemeViewModel.Result = AdditSchemeResult.FindSchemeSuccess;
                editModel.SchemeImportHistory = new List<IScheme> { scheme };
                return View("Manage", editModel);
            }
            else
            {
                return View("Manage", new ManageSchemeViewModel { FindSchemeViewModel = new FindSchemeViewModel { Result = ResultEnum.Failure } });
            }
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [UserAdmit]
        public ActionResult ImportHistory(string schemeName)
        {
            var history = PensionSchemeService.GetImportHistory(schemeName).ToList();
            history.ForEach(x => x.Logo = null);
            return View(history.OrderByDescending(x => x.SchemeData_ImportedOnDate));
        }

        [HttpGet]
        [FusionAuthorize(RoleType.Admin, RoleType.Installer)]
        [UserAdmit]
        public ActionResult Details(int id)
        {
            var scheme = PensionSchemeService.GetSchemeWithDetails(id);

            var model = new SchemeViewModel(scheme);

            return View(model);
        }

        [FusionAuthorize(RoleType.Admin, RoleType.Installer, RoleType.Consultant)]
        [HttpGet]
        public ActionResult CheckFavouriteScheme(string SchemeName)
        {
            var schemeId = 0;
            var scheme = PensionSchemeService.GetSummaryByName(SchemeName);
            if (scheme != null)
                schemeId = scheme.SchemeDetailId;
            var isFavourite = UserProfile.FavouriteSchemes.Any(x => string.Compare(x.SchemeName, SchemeName, true) == 0);
            return Json(new { isFavourite, schemeId }, JsonRequestBehavior.AllowGet);
        }

        private ActionResult delete(AdditSchemeViewModel model)
        {
            bool success = true;
            try
            {
                PensionSchemeService.DeleteById(model.Id);
            }
            catch
            {
                success = false;
            }

            if (success)
            {
                if (Scheme != null && Scheme.SchemeName == model.CurrentSchemeName) Session["UserProfile"] = null;

                TempData.Add("AdditSchemeViewModel", new AdditSchemeViewModel { Result = AdditSchemeResult.DeleteSchemeSuccess });

                return RedirectToAction("Manage");
            }
            else
            {
                model.Result = AdditSchemeResult.DeleteSchemeFailure;
                return View("Manage", new ManageSchemeViewModel { AdditSchemeViewModel = model });
            }
        }
      
        private ActionResult addit(AdditSchemeViewModel model)
        {
            if (Url != null)
                ViewBag.ReturnUrl = Url.Action("Manage");

            #region schemeDataXml
            XDocument schemeDataXml = null;
            try
            {
                schemeDataXml = model.SchemeData != null ? XDocument.Load(model.SchemeData.InputStream) : null;
            }
            catch
            {
                ModelState.AddModelError("SchemeData", "Unable to read XML");
            }
            #endregion
            #region logo
            Image logo = null;

src/Fusion.WebApp/Views/Users/List.cshtml
@model Fusion.WebApp.Models.ManageUserViewModel

@{
    ViewBag.Title = "Manage Users";
    ViewBag.Compact = true;
    ViewBag.HideScheme = true;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
    @Scripts.Render("~/bundles/users-list")
}

<div class="contents-nohead" style="width: 1300px;">
    <section class="grey" style="padding:0px; position: initial;">

        <div class="bottompad">
            @Html.ActionLink("Back", "Manage", null, new { @class = "button" })
        </div>

        <!--section-->
        <div class="grid">
            <!--grid-->
            <div id="user-list-view" class="block lightgrey include_indicator">
                @Html.Partial("_List", Model.ListUserViewModel)
            </div>

        </div><!--grid-->

    </section><!--section-->

</div>

src/Fusion.WebApp/Views/Users/Manage.cshtml
@model Fusion.WebApp.Models.ManageUserViewModel
@{
    var showAdd = string.IsNullOrEmpty(Model.AdditUserViewModel.CurrentUserName);
    ViewBag.Title = showAdd ? "Add User" : "Edit User";
    ViewBag.Compact = true;
    ViewBag.HideScheme = true;
    Layout = "~/Views/Shared/_Layout.cshtml";
}

@section scripts {
    @Scripts.Render("~/bundles/users-manage")
}

<div class="contents loginsection">
    <section id="loginpane" class="admin grey">

        <div class="bottompad">
            <a id="btn-cancel" href="~/Users/Manage" class="button" @Html.VisibleIf(Model.IsEditing)>Cancel</a>
            <a id="btn-home" href='@Url.RouteUrl("Home")' class="button" @Html.VisibleIf(!Model.IsEditing) )>Home</a>
        </div>

        <input type="hidden" name="disable-expanding" value="@Html.JScript().ToBool(!Model.IsEditing)" />

        <!--section-->
        <div class="grid">

            <div id="find-user" class="left fourty-five" style='display:@(Model.IsEditing ? "none" : "block")'>
                <div class="block lightgrey include_indicator">
                    @Html.Partial("_Find", Model.FindUserViewModel)
                </div>
            </div>

            <!--grid-->
            <div id="user-form-container" class='lightgrey @(Model.IsEditing ? "left hundred" : "")'>
                <div id="user-details-section" class='fourty-five @(Model.IsEditing ? "left" : "right")'>
                    <div class="block lightgrey include_indicator">
                        @if (showAdd)
                        {
                            @Html.Partial("_Add", Model.AdditUserViewModel)
                        }
                        else
                        {
                            @Html.Partial("_Edit", Model.AdditUserViewModel)
                        }
                    </div>
                </div>
                <div id="scheme-section" class="right fifty" style='display:@(Model.IsEditing ? "block" : "none")'>
                    <div class="block lightgrey right-continuation">
                        @Html.Partial("_Schemes", Model.AdditUserViewModel)
                    </div>
                </div>
            </div><!--grid-->
        </div>

    </section><!--section-->

</div>

src/Fusion.WebApp/Views/Users/_Add.cshtml
@using FlightDeck.DomainShared
@model Fusion.WebApp.Models.AdditUserViewModel

<h2>Add new user
    @if (Model.Result == AdditUserResult.UserSaveSuccess)
    {
        <span class="changeSucceeded">User saved</span>
    }
    else if (Model.Result == AdditUserResult.DeleteUserSuccess)
    {
        <span class="changeSucceeded">Deleted user</span>
    }
</h2>

@using (Html.BeginForm("Add" , "Users", FormMethod.Post, new { id = "user-form" }))
{
    @Html.AntiForgeryToken()
    
    foreach (var schemeName in Model.Schemes)
    {
        <input type="hidden" name="Schemes" value="@schemeName" />
    }
    
    <div>
        @Html.ValidationMessageFor(m => m.UserName)
        @Html.LabelFor(m => m.UserName)
        @Html.TextBoxFor(m => m.UserName, new { autocomplete = "off" })
    </div>

    <div id="manual-password">
        <div>
            @Html.ValidationMessageFor(m => m.Password)
            @Html.LabelFor(m => m.Password)
            @Html.TextBoxFor(m => m.Password)
        </div>

        <div class="topspace-10">
            @Html.Partial("_PasswordRequirementMessage")
        </div>
    </div>
    
    <div>
        @Html.ValidationMessageFor(m => m.Role)
        @Html.LabelFor(m => m.Role)
        @Html.RoleSelect(Model)
    </div>

    <div>
        @Html.ValidationMessageFor(m => m.FirstName)
        @Html.LabelFor(m => m.FirstName)
        @Html.TextBoxFor(m => m.FirstName)
    </div>

    <div>
        @Html.ValidationMessageFor(m => m.LastName)
        @Html.LabelFor(m => m.LastName)
        @Html.TextBoxFor(m => m.LastName)

    </div>

    <div>
        @Html.ValidationMessageFor(m => m.EmailAddress)
        @Html.LabelFor(m => m.EmailAddress)
        @Html.TextBoxFor(m => m.EmailAddress)
    </div>

    <div class="submitters">

        @if (Model.Result == AdditUserResult.AddUserFailure)
        {
            <span class="changeFailed">Failed to add user</span>
        }
        
        <input type="submit" value="Add new user" id="add-user-btn" class="submit-limit" />

    </div>
}

src/Fusion.WebApp/Views/Users/_Find.cshtml
@model Fusion.WebApp.Models.FindUserViewModel

<h2>Find user</h2>

@using (Html.BeginForm("Find", "Users"))
{
    @Html.AntiForgeryToken()

    <div>
        @Html.ValidationMessageFor(m => m.FindUserName)
        @Html.LabelFor(m => m.FindUserName)
        @Html.TextBoxFor(m => m.FindUserName, new { autocomplete = "off", id = "userSearch", data_usersource = Url.Action("List", "Users") })
    </div>
    <div class="submitters">

        @if (Model.Result == ResultEnum.Failure) { 
            <span class="changeFailed">User not found</span>
        }
        <input type="submit" value="Find User" />
        @Html.ActionLink("List all", "ListAll", null, new { @class = "button" })
    </div>
}

src/Fusion.WebApp/Views/Users/_List.cshtml
@using FlightDeck.DomainShared
@model Fusion.WebApp.Models.ListUserViewModel
@{
    var userHelper = Html.GetUserAdminHelper();
}

@Html.AntiForgeryToken()

<div id="user-list-header-row">
    <div id="h2-user-list" class="left">All Users</div>
    <div id="user-list-search-tools" class="left">
        <div class="left">
            <button id="user-list-filters-toggle" class='@(userHelper.ShowSearchFilter(Model.Params) ? "selected" : "")'>Search tools</button>
        </div>
        <div id="user-list-filters" style='display: @(userHelper.ShowSearchFilter(Model.Params) ? "block" : "none")'>
            <label for="role-filter">Roles</label>
            <select name="role-filter">
                @userHelper.GetRoleFilterOptions(Model.Params)
            </select>
            <label for="scheme-filter">Schemes</label>
            <input type="text" name="scheme-filter" id="scheme-filter" class="scheme-filter" autocomplete="off" value="@(Model.Params.SchemeName ?? string.Empty)" data-schemesource='@Url.Action("List", "Scheme" )' data-url="@userHelper.GetSchemeFilterUrl(Model.Params)" />
            <a id="filter-reset" href='@Url.Action("ListAll", "Users")' class="left-space-20">Reset</a>
        </div>
    </div>
</div>
<div id="user-action-panel">
    <div id="user-bulk-actions">
        <a href="@userHelper.GetFirstPageUrl(Model.Params)" id="delete_user">delete</a>
    </div>
</div>

@if (Model.Users.Any())
{
    <table id="tbl-user-list" class="left-spaced-table">
        <tr>
            <th><input type="checkbox" id="chk-user-selectall" /></th>
            <th><a href='@userHelper.GetNameOrderActionLink(Model.Params)' id="user-list-name-sort">Name</a><span class='user-list-sort-icon user-list-sort-icon-@(Model.Params.NameDescending ? "des" : "asc")'></span></th>
            <th>Email</th>        
            <th>Username</th>
            <th>Role</th>
            <th>Schemes</th>
            <th>Status</th>
        </tr>
        @foreach (var user in Model.Users)
        {
            <tr>
                <td class="user-select hidden"><input type="checkbox" name="user-select-chk" value="@user.Id" /></td>
                <td>@user.Surname, @user.Forename</td>
                <td>@user.Email</td>
                <td>@Html.ActionLink(user.UserName, "Manage", new { id = user.Id })</td>
                <td>@user.Role</td>
                <td>@userHelper.SchemeMembershipDisplay(user)</td>
                <td style="width: 150px;">
                    @if (user.IsLocked)
                    {
                        <img src='@Url.Content("~/Images/user-lock-icon.png")' width="12" height="16" style="padding: 0; margin: 0;" /> <a href="#" class="user-unlock">Unlock</a> <span class="user-unlock-confirmation" style="display: none">[@Html.ActionLink("ok", "Unlock", "Users", new { user.UserName }, new { @class="user-unlock-ok" }) | <a href="#" class="user-unlock-cancel">cancel</a>]</span>
                    }
                </td>
            </tr>
        }
    </table>

    if (Model.Params.TotalMatches > 0)
    {
        <div id="user-list-footer">
            <div style="margin-left:10px; margin-top: 20px;" class="left">
                <div class="paging">
                    @userHelper.GetPagingLinks(Model.Params)
                </div>
            </div>
        </div>
    }

    <div id="dialog-user-delete-confirm" title="">
        <h3>Delete User</h3>
        <p>Are you sure you want to permanently delete selected users?</p>
    </div>
}
else
{
    <p>No users found.</p>
}

src/Fusion.WebApp/Views/Users/_UserAddedEmail.cshtml
@using FlightDeck.DomainShared
@model Fusion.WebApp.Models.UserEmailViewModel

<html>
    <head>
        <style>
            label {
                width: 100px;
                display:inline-block;
            }
        </style>
    </head>
    <body>
        <h2>Welcome!</h2>
    
        <p>You have been registered as a @Model.Role.DisplayName() of KPMG Fusion.</p>
     
        <p>
            <label>Username:</label><b>@Model.UserName</b><br/>
            <label>First name:</label><b>@Model.FirstName</b><br />
            <label>Last name:</label><b>@Model.LastName</b><br />
            <label>Email address:</label><b>@Model.EmailAddress</b><br />
        </p>
        
        <p>Please follow the link below to complete your registration and access the application.</p>

        <a href="@Url.Action("ResetPassword", "Account", new {username = Model.UserName, token = Model.Token }, "http")">KPMG Fusion - Start Here</a>

    </body>
</html>